server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/psychologicalcounselingplatform?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  redis:
    host: localhost
    port: 6379
    # 设置key过期扫描
    config:
      maxmemory-policy: volatile-lru
    
  mybatis-plus:
    type-aliases-package: PsychologicalCounselingPlatform.entity
    configuration:
      map-underscore-to-camel-case: true
    global-config:
      db-config:
        id-type: ASSIGN_ID
      
jwt:
  # 使用更长的密钥（至少32字节/256位）
  secret: bXlfc3VwZXJfc2VjcmV0X2tleV9mb3JfandfdG9rZW5fZ2VuZXJhdGlvbl8yNTZfYml0c19sb25nX2Vub3VnaA==
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
